spring:
  application:
    name: finance-ledger

server:
  port: 5555
  servlet:
    context-path: /financeledger
  error:
    include-message: always

logging:
  level:
    root: error
    org.springframework: error
    ua.pp.salnikov.financeledger: debug
  file:
    path: ./
    name: financeledger.log
  logback:
    rollingpolicy:
      file-name-pattern: ${LOG_FILE}.%d{yyyy-MM-dd}.%i.gz
  pattern:
    file: '%d{ISO8601} [%-5p] [%25.25c{0}] - %m%n'
    console: '%black(%d{ISO8601}) [%highlight(%-5p)] [%yellow(%25.25c{0})] - %m%n'
